package com.chihuo.bussiness;

// Generated 2012-2-14 22:19:35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Chef generated by hbm2java
 */
public class Chef implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private String specialty;
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);

	public Chef() {
	}

	public Chef(String name, String description, String specialty,
			Set<OrderItem> orderItems) {
		this.name = name;
		this.description = description;
		this.specialty = specialty;
		this.orderItems = orderItems;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

}
