package com.chihuo.bussiness;

// Generated 2012-2-22 16:09:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DataLog generated by hbm2java
 */
public class DataLog implements java.io.Serializable {

	private Integer id;
	private String dataTable;
	private Integer did;
	private Date addTime;
	private Date updateTime;
	private Date update2Time;
	private Date deleteTime;

	public DataLog() {
	}

	public DataLog(String dataTable, Integer did, Date addTime,
			Date updateTime, Date update2Time, Date deleteTime) {
		this.dataTable = dataTable;
		this.did = did;
		this.addTime = addTime;
		this.updateTime = updateTime;
		this.update2Time = update2Time;
		this.deleteTime = deleteTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDataTable() {
		return this.dataTable;
	}

	public void setDataTable(String dataTable) {
		this.dataTable = dataTable;
	}

	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Date getUpdate2Time() {
		return this.update2Time;
	}

	public void setUpdate2Time(Date update2Time) {
		this.update2Time = update2Time;
	}

	public Date getDeleteTime() {
		return this.deleteTime;
	}

	public void setDeleteTime(Date deleteTime) {
		this.deleteTime = deleteTime;
	}

}
