package com.chihuo.bussiness;

// Generated 2012-2-14 22:19:35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Rating generated by hbm2java
 */
public class Rating implements java.io.Serializable {

	private Integer id;
	private Integer star;
	private String description;
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);

	public Rating() {
	}

	public Rating(Integer star, String description, Set<OrderItem> orderItems) {
		this.star = star;
		this.description = description;
		this.orderItems = orderItems;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getStar() {
		return this.star;
	}

	public void setStar(Integer star) {
		this.star = star;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

}
