package com.chihuo.bussiness;

// Generated 2012-2-14 22:19:35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Require generated by hbm2java
 */
public class Require implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<RequireRel> requireRels = new HashSet<RequireRel>(0);

	public Require() {
	}

	public Require(String name, Set<RequireRel> requireRels) {
		this.name = name;
		this.requireRels = requireRels;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<RequireRel> getRequireRels() {
		return this.requireRels;
	}

	public void setRequireRels(Set<RequireRel> requireRels) {
		this.requireRels = requireRels;
	}

}
