package com.chihuo.bussiness;

// Generated 2012-2-14 22:19:35 by Hibernate Tools 3.4.0.CR1

/**
 * RequireRel generated by hbm2java
 */
public class RequireRel implements java.io.Serializable {

	private Integer id;
	private Require require;
	private OrderItem orderItem;

	public RequireRel() {
	}

	public RequireRel(Require require, OrderItem orderItem) {
		this.require = require;
		this.orderItem = orderItem;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Require getRequire() {
		return this.require;
	}

	public void setRequire(Require require) {
		this.require = require;
	}

	public OrderItem getOrderItem() {
		return this.orderItem;
	}

	public void setOrderItem(OrderItem orderItem) {
		this.orderItem = orderItem;
	}

}
