package com.chihuo.bussiness;

// Generated 2012-2-14 22:19:35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tags generated by hbm2java
 */
public class Tags implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set<TagsRel> tagsRels = new HashSet<TagsRel>(0);

	public Tags() {
	}

	public Tags(String name) {
		this.name = name;
	}

	public Tags(String name, String description, Set<TagsRel> tagsRels) {
		this.name = name;
		this.description = description;
		this.tagsRels = tagsRels;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<TagsRel> getTagsRels() {
		return this.tagsRels;
	}

	public void setTagsRels(Set<TagsRel> tagsRels) {
		this.tagsRels = tagsRels;
	}

}
