package com.chihuo.bussiness;

// Generated 2012-2-14 22:19:35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tools generated by hbm2java
 */
public class Tools implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<ToolsRel> toolsRels = new HashSet<ToolsRel>(0);

	public Tools() {
	}

	public Tools(String name) {
		this.name = name;
	}

	public Tools(String name, Set<ToolsRel> toolsRels) {
		this.name = name;
		this.toolsRels = toolsRels;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<ToolsRel> getToolsRels() {
		return this.toolsRels;
	}

	public void setToolsRels(Set<ToolsRel> toolsRels) {
		this.toolsRels = toolsRels;
	}

}
