package com.chihuo.bussiness;

// Generated 2012-2-14 22:19:35 by Hibernate Tools 3.4.0.CR1

/**
 * ToolsRel generated by hbm2java
 */
public class ToolsRel implements java.io.Serializable {

	private Integer id;
	private Tools tools;
	private Order order;
	private Integer number;

	public ToolsRel() {
	}

	public ToolsRel(Tools tools, Order order, Integer number) {
		this.tools = tools;
		this.order = order;
		this.number = number;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Tools getTools() {
		return this.tools;
	}

	public void setTools(Tools tools) {
		this.tools = tools;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

}
